version: '3.8'

services:
  web:
    image: glaxer/python-oc-lettings-fr-web
    container_name: p13_python_oc
    command: gunicorn oc_lettings_site.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app