# Generated by Django 3.0 on 2023-07-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addresse',
        ),
        migrations.RenameField(
            model_name='letting',
            old_name='address',
            new_name='addresse',
        ),
    ]
