name: Workflow P13 Python OC

on:
  push:
    branches:
      - test

jobs:
  django-tests-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: python manage.py test

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker-compose build
          docker tag python-oc-lettings-fr_web:latest glaxer/python-oc-lettings-fr_web:latest
          docker push glaxer/python-oc-lettings-fr_web:latest

  deploy:
    runs-on: ubuntu-latest  # Utilisez l'image Ubuntu par défaut

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OVH_IP }}
          username: ${{ secrets.OVH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./nginx, docker-compose.yml"
          target: "/home/ubuntu/myriam/"
          script: |
            cd /home/ubuntu/apps
            docker-compose down -v
            docker-compose up -d --build
